// MOTOR PREFERENCES //
// Drivetrain - Port Mappings
#define LEFT_MOTOR_PORT_1 14
#define LEFT_MOTOR_PORT_2 15

#define RIGHT_MOTOR_PORT_1 4
#define RIGHT_MOTOR_PORT_2 2

// Drivetrain - Gearset
#define LEFT_MOTOR_1_GEARSET E_MOTOR_GEARSET_18
#define LEFT_MOTOR_2_GEARSET E_MOTOR_GEARSET_18

#define RIGHT_MOTOR_1_GEARSET E_MOTOR_GEARSET_18
#define RIGHT_MOTOR_2_GEARSET E_MOTOR_GEARSET_18

// Rollers - Port Mappings
#define FRONT_ROLLER_PORT_1 8
#define FRONT_ROLLER_PORT_2 16

#define MIDDLER_ROLLER_PORT 6

#define BACK_ROLLER_PORT 18

// Rollers - Gearset
#define FRONT_ROLLER_1_GEARSET E_MOTOR_GEARSET_18
#define FRONT_ROLLER_2_GEARSET E_MOTOR_GEARSET_18

#define MIDDLER_ROLLER_GEARSET E_MOTOR_GEARSET_18

#define BACK_ROLLER_GEARSET E_MOTOR_GEARSET_18

// SOLENOID PREFERNCES // 
// Blocker - Port Mappings
#define BLOCKER_PORT {{7, 'A'}}

// Grabber - Port Mappings
#define GRABBER_PORT {{7, 'B'}}

// SENSOR PREFERENCES //
#define LEFT_DISTANCE_SENSOR_PORT 20
#define RIGHT_DISTANCE_SENSOR_PORT 3
#define OPTIMAL_DISTANCE_LEFT 246
#define OPTIMAL_DISTANCE_RIGHT 272

// DRIVING PREFERENCES //
#define DRIVE_SPEED 100
#define TURN_SPEED 70

// CONTROL PREFERENCES //

// Controller - Drive Axis Mappings
#define DRIVE_AXIS_CONTROLLER_X E_CONTROLLER_ANALOG_LEFT_X
#define DRIVE_AXIS_CONTROLLER_Y E_CONTROLLER_ANALOG_LEFT_Y

// Controller - Roller Button Mappings
#define ROLLER_FRONT_FWD_BUTTON E_CONTROLLER_DIGITAL_L2
#define ROLLER_FRONT_REV_BUTTON E_CONTROLLER_DIGITAL_L1

#define ROLLER_LAUNCH_FWD_BUTTON E_CONTROLLER_DIGITAL_R1
#define ROLLER_LAUNCH_REV_BUTTON E_CONTROLLER_DIGITAL_R2

#define ROLLER_FEEDER_TOGGLE_BUTTON E_CONTROLLER_DIGITAL_A

// Controller - Blocker Button Mappings
#define BLOCKER_TOGGLE_BUTTON E_CONTROLLER_DIGITAL_UP

// Controller - Grabber Button Mappings
#define GRABBER_TOGGLE_BUTTON E_CONTROLLER_DIGITAL_LEFT

// Controller - Replay Button Mappings
#define REPLAY_RECORD_BUTTON E_CONTROLLER_DIGITAL_DOWN
